pipeline {
    agent any
    stages {
    stage('Clone') { // for display purposes
        // Clone the configurations repository
        steps {
          cleanWs()
          git 'https://github.com/HoldemGK/terraform-examples.git' 
        }  
    }
    stage('Download') {
        // Download Terraform
        steps {
          sh label: '', script: 'curl https://releases.hashicorp.com/terraform/1.2.8/terraform_1.2.8_linux_amd64.zip \
            --output terraform_1.2.8_darwin_amd64.zip \
            && unzip terraform_1.2.8_darwin_amd64.zip'
        }
    }
    stage('Backend-Init') {
        // Initialize the Terraform configuration
        steps {
          dir('03_02-03_remotestate/remote_resources') {
          sh script: '../../terraform init -input=false'
          }
        }
    }/*
    stage('Backend-Plan') {
        // Create Terraform plan for backend resources
        steps {
          withCredentials([string(credentialsId: 'AWS_ACCESS_KEY', variable: 'aws_access_key'), 
                        string(credentialsId: 'AWS_SECRET_KEY', variable: 'aws_secret_key')]) {
            dir('03_02-03_remotestate/remote_resources') {
                sh script: '../../terraform plan \
                        -out backend.tfplan \
                        -var="aws_access_key=$aws_access_key" \
                        -var="aws_secret_key=$aws_secret_key"'
            }
        }
        }
    }
    stage('Backend-Apply') {
        steps {
          withCredentials([string(credentialsId: 'AWS_ACCESS_KEY', variable: 'aws_access_key'), 
                        string(credentialsId: 'AWS_SECRET_KEY', variable: 'aws_secret_key')]) {
                            dir('03_02-03_remotestate/remote_resources') {
                                sh script: '../../terraform apply backend.tfplan'
                            }
        }
        }
    }*/
    stage('Config-Init') {
        steps {
          withCredentials([string(credentialsId: 'AWS_ACCESS_KEY', variable: 'aws_access_key'), 
                        string(credentialsId: 'AWS_SECRET_KEY', variable: 'aws_secret_key')]) {
                            dir('03_02-03_remotestate') {
                                sh script: '../terraform init \
                                            -backend-config="bucket=red30-tfstate-gk" \
                                            -backend-config="key=red30/ecommerceapp/app.state" \
                                            -backend-config="region=us-east-1" \
                                            -backend-config="dynamodb_table=red30-tfstatelock" \
                                            -backend-config="access_key=$aws_access_key" \
                                            -backend-config="secret_key=$aws_secret_key"'
                            }
                        }
        }
    }
    stage('Config-Plan') {
        // Generate Terraform plan
        steps {
          withCredentials([string(credentialsId: 'AWS_ACCESS_KEY', variable: 'aws_access_key'), 
                        string(credentialsId: 'AWS_SECRET_KEY', variable: 'aws_secret_key')]) {
                            dir('03_02-03_remotestate') {
                                sh script: '../terraform plan \
                                            -out s1.tfplan \
                                            -var="aws_access_key=$aws_access_key" \
                                            -var="aws_secret_key=$aws_secret_key"'
                            }
        }
        }
    }
    stage('Config-Apply') {
        // Apply the configuration
        steps {
          withCredentials([string(credentialsId: 'AWS_ACCESS_KEY', variable: 'aws_access_key'), 
                        string(credentialsId: 'AWS_SECRET_KEY', variable: 'aws_secret_key')]) {
                            dir('03_02-03_remotestate') {
                                sh script: '../terraform apply s1.tfplan'
                            }
        }
        }
    }
    stage('Destroy'){
        steps {
          input 'Destroy?'
          withCredentials([string(credentialsId: 'AWS_ACCESS_KEY', variable: 'aws_access_key'), 
                        string(credentialsId: 'AWS_SECRET_KEY', variable: 'aws_secret_key')]) {
            dir('03_02-03_remotestate') {
                sh script: '../terraform destroy \
                        -auto-approve \
                        -var="aws_access_key=$aws_access_key" \
                        -var="aws_secret_key=$aws_secret_key"'
            }
            dir('03_02-03_remotestate/remote_resources') {
                sh script: '../../terraform destroy \
                        -auto-approve \
                        -var="aws_access_key=$aws_access_key" \
                        -var="aws_secret_key=$aws_secret_key"'
            }
        }
        }
    }
}
}